### PR TITLE
added hover states for buttons

### PR DESCRIPTION
**Pull request by awelllle**
#61 
I switched to Font Awesome for the icons cos the previous ones were images.

I added Font Awesome through Git Submodules

### CODE REVIEW

**Comment by RichardLitt** [comment]
These should also be changed for the Learn More, Our Mission, and Offer Help sections. Otherwise, good work!

**Comment by awelllle** [comment]
oh, yeah. I missed that. I'll make the changes now

**Comment by awelllle** [comment]
also decided to do for the banner button also, if that's okay

**Comment by awelllle** [comment]
Threw in something for the banner button while I was at it. What do you think?

**Comment by RichardLitt** [comment]
Looks great to me. @Erioldoesdesign The yellow is hard to read on hover: is that OK, from a UX perspective?

**Comment by Erioldoesdesign** [comment]
Hover functionality is *slick* @awelllle , nice job!

One thing that is totally my bad is I didn't provide visuals in #61 that covers the lower contrast colours yellow/green. Totally my oversight/bad and I'll make an issue with mock to reflect that so no reason why this PR can't be merged and an improvement ticket made for the contrast of the yellow/green

**Comment by RichardLitt** [comment]
Thank you, @awelllle! Good job. :)

**Pull request merged**
