### PR TITLE
Web implementation of the blog page layouts

### LINKED ISSUE #36: Create the blog page design for fossresponders.com
Fossresponders are looking to cross-post blog content to their site and require a new page design/layout for articles/blog pieces.

Developers will implement the blog in Jekyll.

This is the first article that will be cross-posted:
https://engineering.indeedblog.com/blog/2020/03/support-the-oss-community/

The blog pages should layout text well, readable with appropriate headings and ability to share the blog post on social media.
The brand styling should be used in the design but the brand styles can be extended and developed to support this new kind of page content/context.

Ability to sort by and add categories for articles.

Fossresponders website team - please add other requirements/considerations for design in this issue or in comments on this issue :)

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #36 
Refs #49 

Fixed certain things in #49 that were missing or were breaking the current change. I have based it on top of that PR and rebased it with masters to fix the merge conflicts.

I have left some comments in the issue ticket about certain implementations and how to go about it in design perspective. Once I have more idea about that, I will go ahead and complete.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Am I blocking you at all here, @SaptakS? :)

**Comment by SaptakS** [comment]
Hey @RichardLitt . Not really. I am waiting for some answers here: https://github.com/foss-responders/fossresponders.com/issues/36#issuecomment-621415888 :sweat_smile:

**Comment by SaptakS** [comment]
@RichardLitt Just added some stuff. 

Things done:
- [x] Showing the latest blog posts (most recent 2 posts) in [blog index page](https://deploy-preview-79--fossresponders.netlify.app/blog/)
- [x] Showing all remaining blogs in a 3 column grid below it
- [x] Individual post [pages](https://deploy-preview-79--fossresponders.netlify.app/angel_donors/test1/)
- [x] Category [pages](https://deploy-preview-79--fossresponders.netlify.app/category/cancelled_conference/)
- [x] Author [pages](https://deploy-preview-79--fossresponders.netlify.app/authors/richardlitt/)

Things to be done:
- [ ] Responsiveness off all the pages
- [ ] The different sections in the blog index page. I left few questions related to that in the issue.
- [ ] The recommended blogs and social media shown in individual posts. Not sure how we should go about it.

Apart from the responsiveness (which I will get done by tonight) I don't think anything else should be much of a blocker for immediate posts right now and can be done iteratively if needed.

**Comment by RichardLitt** [comment]
Thanks, @SaptakS. This is good work! It's not ready yet according to the spec, however. More to do:

- [ ] Social icons aren't loading for me.
- [ ] Remove Discus (It's not in the designs)
- [ ] Make responsive. An unresponsive site doesn't work.
- [ ] Make footer sticky
- [ ] Fix alignment of blog logo (see screenshot)

Screen Shot 2020-05-04 at 14 33 29

- [ ] Make padding on date subtext match the spec; more bottom padding.
- [ ] Lineheight for titles doesn't match spec.
- [ ] Remove underline from author and category links
- [ ] Add in breadcrumbs
- [ ] Remove "previous post" navs
- [ ] Rebase on master. Why was index.md changed?

**Comment by RichardLitt** [comment]
- [ ] Add in author attribution in "Posted on" section
- [ ] Limit text to something like 800px (large screens is really too big)
Screen Shot 2020-05-04 at 14 40 31

**Comment by SaptakS** [comment]
@RichardLitt thanks for the review. I will get those done.

**Comment by RichardLitt** [comment]
Thank you, @SaptakS! Merged. Awesome.

**Pull request merged**
