### PR TITLE
Reducing to 3 buttons and updating the first to point to the Google form

### PR DESCRIPTION
**Pull request by tmurso**
Reducing to 3 buttons and updating the first to point to the Google form

@RichardLitt could you review?

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks good to me!

**Comment by RichardLitt** [comment]
Will merge at 1700 PDT, 2000 EDT.

**Comment by DuaneOBrien** [comment]
LGTM

**Comment by RichardLitt** [comment]
Merged. Thanks, @tmurso

**Pull request merged**
