### PR TITLE
Edit events section

### PR DESCRIPTION
**Pull request by RichardLitt**
Changed copy.

### CODE REVIEW

**Review by Erioldoesdesign — COMMENTED** [review]
https://docs.google.com/forms/d/e/1FAIpQLSeo7NwDVs9O1JJ9cVZmypEiw50lEuot7gu3-dqOswr2dazUzg/viewform

Other than the google form for organisations that have had financial losses not working this looks good to me :)

**Comment by awright** [comment]
you are awesome!

**Comment by RichardLitt** [comment]
@Erioldoesdesign that's commented out. So, shouldn't be an issue. Thanks, both of you. :)

**Comment by Erioldoesdesign** [comment]
@RichardLitt doh haha I see the comment out now 🤦

**Pull request merged**
