### PR TITLE
Makes the header style specific for blog posts

### LINKED ISSUE #88: Privacy Policy changed due to blog css
Looks like the style for the Policy Policy header has been changed. 

https://fossresponders.com/privacy/

### PR DESCRIPTION
**Pull request by SaptakS**
Should Fix #88

### CODE REVIEW

**Comment by SaptakS** [comment]
@RichardLitt let me know if this fixes the issue.

**Comment by RichardLitt** [comment]
It does!

Since it fits  - can you add the Privacy Policy link to the footer for the blogs, too?

**Comment by SaptakS** [comment]
And should be done!

**Comment by RichardLitt** [comment]
Thank you! Good work. :)

**Pull request merged**
