### PR TITLE
WIP: Add blog

### LINKED ISSUE #36: Create the blog page design for fossresponders.com
Fossresponders are looking to cross-post blog content to their site and require a new page design/layout for articles/blog pieces.

Developers will implement the blog in Jekyll.

This is the first article that will be cross-posted:
https://engineering.indeedblog.com/blog/2020/03/support-the-oss-community/

The blog pages should layout text well, readable with appropriate headings and ability to share the blog post on social media.
The brand styling should be used in the design but the brand styles can be extended and developed to support this new kind of page content/context.

Ability to sort by and add categories for articles.

Fossresponders website team - please add other requirements/considerations for design in this issue or in comments on this issue :)

### PR DESCRIPTION
**Pull request by CarlSchwan**
Fixes #36

### CODE REVIEW

**Comment by CarlSchwan** [comment]
rebased on top of the feat/redesign branch.

**Comment by RichardLitt** [comment]
Thanks, @ognarb! Awesome start!

I've merged the other PR, so you should be good to go to copy the footer, etc, from there. :) Let me know if you need help with anything.

**Comment by RichardLitt** [comment]
@ognarb Is this ready, you think? :)

**Comment by CarlSchwan** [comment]
No yet, that's missing is polishing and the layout for the tag pages. I try to work on it tomorrow.

**Comment by RichardLitt** [comment]
@ognarb Were you able to get more progress done on this?

**Comment by RichardLitt** [comment]
Heyo. I'm having issues running this locally:

```
➜  fossresponders.com git:(ognarb-blog) bees
Configuration file: /Users/richard/src/foss-responders/fossresponders.com/_config.yml
            Source: /Users/richard/src/foss-responders/fossresponders.com
       Destination: /Users/richard/src/foss-responders/fossresponders.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
         AutoPages: Generating tags pages
Error reading file /Users/richard/src/foss-responders/fossresponders.com/_layouts/autopage_tags.html: No such file or directory @ rb_sysopen - /Users/richard/src/foss-responders/fossresponders.com/_layouts/autopage_tags.html
Error reading file /Users/richard/src/foss-responders/fossresponders.com/_layouts/autopage_tags.html: No such file or directory @ rb_sysopen - /Users/richard/src/foss-responders/fossresponders.com/_layouts/autopage_tags.html
         AutoPages: Generating categories pages
         AutoPages: Generating collections pages
Error reading file /Users/richard/src/foss-responders/fossresponders.com/_layouts/autopage_collection.html: No such file or directory @ rb_sysopen - /Users/richard/src/foss-responders/fossresponders.com/_layouts/autopage_collection.html
        Pagination: Complete, processed 5 pagination page(s)
  Liquid Exception: Could not locate the included file 'logo.html' in any of ["/Users/richard/src/foss-responders/fossresponders.com/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /_layouts/home.html
jekyll 3.8.5 | Error:  Could not locate the included file 'logo.html' in any of ["/Users/richard/src/foss-responders/fossresponders.com/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
```

Any ideas? Also, is there any chance you have an ETA for this work?

**Comment by SaptakS** [comment]
@RichardLitt I am taking a look at this branch.

**Comment by RichardLitt** [comment]
Superseded by #79. Thanks, @ognarb, for your initial help!

**Pull request closed without merging**
